export const ADD_CAROUSEL = 'ADD_CAROUSEL';
export const CAROUSEL_LOADING = 'CAROUSEL_LOADING';
export const CAROUSEL_FAILED = 'CAROUSEL_FAILED';

export const ADD_HOSTS = 'ADD_HOSTS';
export const HOSTS_LOADING = 'HOSTS_LOADING';
export const HOSTS_FAILED = 'HOSTS_FAILED';

export const ADD_GUESTS = 'ADD_GUESTS';
export const GUESTS_LOADING = 'GUESTS_LOADING';
export const GUESTS_FAILED = 'GUESTS_FAILED';

